export interface Login {
    isValid: true;
    message: string;
    email: string;                    // Email address of the student
    studentPassword: string;          // Password of the student (will be encrypted on the backend)
}
export interface UserMasterModel {
    countryCode: string;
    confirmPassword: string;
    userID?: number; // Optional because it's generated by the backend
    firstName: string;
    lastName: string;
    email: string;
    userTypeID: number; // Assign a default or dynamic value as required
    userName: string;
    userPassword: string;
    createdOn?: string; // Optional because it's often auto-generated
    createdBy?: number; // Optional because it's backend-assigned
    modifiedOn?: string; // Optional
    modifiedBy?: number; // Optional
    userMasterStatus: number; // Example: 1 for active, 0 for inactive
  }
  
  